### ISSUE TITLE
Ctrl-End followed by Ctrl-Del makes the vello_editor example panic

### ISSUE THREAD

**Issue by PoignardAzur** [linebender/parley#179]
Not much else to say. Steps to reproduce:

- `cargo run --bin vello_editor`
- Press Ctrl-End (cursor goes to the very end of text).
- Press Ctrl-Delete.

The example panics with this message:

```
thread 'main' panicked at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/alloc/src/vec/mod.rs:2207:36:
slice index starts at 1120 but ends at 1119
```

<details>

<summary>Stack trace</summary>

```
stack backtrace:
   0: rust_begin_unwind
             at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/panicking.rs:662:5
   1: core::panicking::panic_fmt
             at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/core/src/panicking.rs:74:14
   2: core::slice::index::slice_index_order_fail_rt
             at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/core/src/slice/index.rs:85:5
   3: core::slice::index::slice_index_order_fail
             at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/core/src/slice/index.rs:78:5
   4: core::slice::index::range
             at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/core/src/slice/index.rs:893:9
   5: alloc::vec::Vec<T,A>::drain
             at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/alloc/src/vec/mod.rs:2207:36
   6: alloc::vec::Vec<T,A>::splice
             at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/alloc/src/vec/mod.rs:3180:25
   7: alloc::string::String::replace_range
             at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/alloc/src/string.rs:1934:9
   8: parley::layout::editor::PlainEditorTxn<T>::delete_word
             at ./parley/src/layout/editor.rs:171:13
   9: vello_editor::text::Editor::handle_event::{{closure}}
             at ./examples/vello_editor/src/text.rs:210:29
  10: parley::layout::editor::PlainEditor<T>::transact
             at ./parley/src/layout/editor.rs:515:9
  11: vello_editor::text::Editor::transact
             at ./examples/vello_editor/src/text.rs:39:9
  12: vello_editor::text::Editor::handle_event
             at ./examples/vello_editor/src/text.rs:208:53
  13: <vello_editor::SimpleVelloApp as winit::application::ApplicationHandler<accesskit_winit::Event>>::window_event
             at ./examples/vello_editor/src/main.rs:215:9
  14: winit::event_loop::dispatch_event_for_app
             at /home/olivier-faure/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.30.5/src/event_loop.rs:642:52
  15: winit::event_loop::EventLoop<T>::run_app::{{closure}}
             at /home/olivier-faure/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.30.5/src/event_loop.rs:265:49
  16: core::ops::function::impls::<impl core::ops::function::FnMut<A> for &mut F>::call_mut
             at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/core/src/ops/function.rs:294:13
  17: core::ops::function::impls::<impl core::ops::function::FnMut<A> for &mut F>::call_mut
             at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/core/src/ops/function.rs:294:13
  18: winit::platform_impl::linux::x11::EventLoop<T>::drain_events::{{closure}}
             at /home/olivier-faure/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.30.5/src/platform_impl/linux/x11/mod.rs:593:21
  19: core::ops::function::impls::<impl core::ops::function::FnMut<A> for &mut F>::call_mut
             at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/core/src/ops/function.rs:294:13
  20: core::ops::function::impls::<impl core::ops::function::FnMut<A> for &mut F>::call_mut
             at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/core/src/ops/function.rs:294:13
  21: winit::platform_impl::linux::x11::event_processor::EventProcessor::xinput_key_input
             at /home/olivier-faure/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.30.5/src/platform_impl/linux/x11/event_processor.rs:959:17
  22: winit::platform_impl::linux::x11::event_processor::EventProcessor::process_xevent
             at /home/olivier-faure/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.30.5/src/platform_impl/linux/x11/event_processor.rs:183:17
  23: winit::platform_impl::linux::x11::event_processor::EventProcessor::process_event
             at /home/olivier-faure/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.30.5/src/platform_impl/linux/x11/event_processor.rs:79:9
  24: winit::platform_impl::linux::x11::EventLoop<T>::drain_events
             at /home/olivier-faure/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.30.5/src/platform_impl/linux/x11/mod.rs:584:13
  25: winit::platform_impl::linux::x11::EventLoop<T>::single_iteration
             at /home/olivier-faure/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.30.5/src/platform_impl/linux/x11/mod.rs:520:9
  26: winit::platform_impl::linux::x11::EventLoop<T>::poll_events_with_timeout
             at /home/olivier-faure/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.30.5/src/platform_impl/linux/x11/mod.rs:504:9
  27: winit::platform_impl::linux::x11::EventLoop<T>::pump_events
             at /home/olivier-faure/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.30.5/src/platform_impl/linux/x11/mod.rs:424:13
  28: winit::platform_impl::linux::x11::EventLoop<T>::run_on_demand
             at /home/olivier-faure/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.30.5/src/platform_impl/linux/x11/mod.rs:385:19
  29: winit::platform_impl::linux::EventLoop<T>::run_on_demand
             at /home/olivier-faure/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.30.5/src/platform_impl/linux/mod.rs:813:56
  30: winit::platform_impl::linux::EventLoop<T>::run
             at /home/olivier-faure/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.30.5/src/platform_impl/linux/mod.rs:806:9
  31: winit::event_loop::EventLoop<T>::run_app
             at /home/olivier-faure/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.30.5/src/event_loop.rs:265:9
  32: vello_editor::main
             at ./examples/vello_editor/src/main.rs:353:5
  33: core::ops::function::FnOnce::call_once
             at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/core/src/ops/function.rs:250:5
```
</details>

**Comment by DJMcNab** [comment]
We'll need to check this again after #170

**Comment by dfrg** [comment]
This doesn't appear to reproduce in #170

**Comment by PoignardAzur** [comment]
Can't reproduce in #170.
